spring.application.name=auth-service

server.port=8090

# Load local .env configuration
spring.config.import=optional:file:.env[.properties]

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

# JWT
jwt.secretKey=${JWT_SECRET_KEY}

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}

# Actuator
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=when_authorized

# Logging
logging.level.root=INFO
logging.level.com.company.MakeMyTrip.Auth_service=INFO