spring.application.name=auth-service

server.port=8090


spring.datasource.url=jdbc:postgresql://localhost:5432/makemytrip_authdb
spring.datasource.username=postgres
spring.datasource.password=yash8252


spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

jwt.secretKey=mysupersecurekeyformysafarsaathijwt1234567890abcdefABCDEF1234567890

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=when_authorized

logging.level.root=INFO
logging.level.com.company.MakeMyTrip.Auth_service=INFO

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false