spring.application.name=Auth-service


server.port=8090
spring.datasource.url=jdbc:postgresql://localhost:5432/makemytrip_authdb

spring.datasource.username=postgres
spring.datasource.password=yash8252

spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost

# Actuator
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=when_authorized

# Logging
logging.level.root=INFO
logging.level.com.company.MakeMyTrip.Auth_service=INFO


#kafka
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.producer.properties.spring.json.add.type.headers=false


jwt.secretKey=mysupersecurekeyformysafarsaathijwt1234567890abcdefABCDEF1234567890