spring.application.name=pricing-service

server.port=8094
spring.datasource.url=jdbc:postgresql://localhost:5432/makemytrip_pricingdb

spring.datasource.username=postgres
spring.datasource.password=yash8252

spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


booking.service.url=http://localhost:8093
