spring.application.name=payment-service


server.port=8095

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/makemytrip_paymentdb
spring.datasource.username=postgres
spring.datasource.password=yash8252
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost


razorpay.keyId=rzp_test_RQVaEMpPFKIRiu
razorpay.keySecret=tmKnTRgjd9xLF7EfkUS7nF1t



spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.consumer.group-id=payment-service
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.consumer.enable-auto-commit=false

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=com.company.MakeMyTrip.events
spring.kafka.consumer.properties.spring.json.use.type.headers=false