spring.application.name=review-service




server.port=8096

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/makemytrip_reviewdb
spring.datasource.username=postgres
spring.datasource.password=yash8252
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost